Log mongoose validation errors generated during createItems(improvement).
At least, on windows keystone has issues generating mongoose validation errors when they happen during createItems.  To address this issue createItems errors need to be logged very early on within its own module and not back in the updates module where the process.exit() happens since it has higher priority than logging and thus most times preempts any logging that may still be queued up.  The code arrangement provided by this PR ensures the best consistent results.

##With the updated changes, if a validation or other error or occurs createItems will log an error.  For example:

    { [ValidationError: Validation failed]
      message: 'Validation failed',
      name: 'ValidationError',
      errors:
       { startTime:
          { [ValidatorError: Path `startTime` is required.]
            message: 'Path `startTime` is required.',
            name: 'ValidatorError',
            path: 'startTime',
            type: 'required',
            value: undefined } },
      model: 'Event',
      data:
       { name: 'Test Booking 1',
         status: 'pending',
         endTime:
          { _isAMomentObject: true,
            _isUTC: false,
            _pf: [Object],
            _locale: [Object],
            _d: Thu Jan 08 2015 21:29:37 GMT-0500 (Eastern Standard Time) },
         __ref: 'Event_1',
         __doc:
          { endTime: Thu Jan 08 2015 21:29:37 GMT-0500 (Eastern Standard Time),
            name: 'Test Booking 1',
            type: 'none',
            repeat: 'none',
            status: 'pending',
            guests: [],
            allDay: false,
            listName: 'Event',
            _id: 54af3d139844182c0ff75cea } } }
    Trace: ValidationError: Path `startTime` is required.
        at model.Document.invalidate (c:\reDist\node_modules\keystone\node_modules\mongoose\lib\document.js:1021:32)
        at c:\reDist\node_modules\keystone\node_modules\mongoose\lib\document.js:970:16
        at validate (c:\reDist\node_modules\keystone\node_modules\mongoose\lib\schematype.js:610:7)
        at c:\reDist\node_modules\keystone\node_modules\mongoose\lib\schematype.js:627:9
        at Array.forEach (native)
        at SchemaDate.SchemaType.doValidate (c:\reDist\node_modules\keystone\node_modules\mongoose\lib\schematype.js:614:19)
        at c:\reDist\node_modules\keystone\node_modules\mongoose\lib\document.js:968:9
        at process._tickCallback (node.js:419:13)
        at c:\reDist\node_modules\keystone\lib\core\createItems.js:295:13
        at c:\avp\node_modules\async\lib\async.js:544:30
        at c:\avp\node_modules\async\lib\async.js:151:21
        at c:\avp\node_modules\async\lib\async.js:151:21
        at c:\reDist\node_modules\keystone\lib\core\createItems.js:120:7
        at handleError (c:\reDist\node_modules\keystone\node_modules\mongoose\node_modules\hooks\hooks.js:92:18)
        at _next (c:\reDist\node_modules\keystone\node_modules\mongoose\node_modules\hooks\hooks.js:34:22)
        at fnWrapper (c:\reDist\node_modules\keystone\node_modules\mongoose\node_modules\hooks\hooks.js:159:8)
        at complete (c:\reDist\node_modules\keystone\node_modules\mongoose\lib\document.js:986:5)
        at c:\reDist\node_modules\keystone\node_modules\mongoose\lib\document.js:977:20

##With the updated changes, if a createItems error occurs the updates module will log a final error.  For example:

    ------------------------------------------------

    avp: Update 0.0.1-avp failed with errors:

    ValidationError: Path `startTime` is required.

##If createItems succeeds then you get the usual.  For example:

    ------------------------------------------------
    avp: Successfully applied update 0.0.1-avp.

    Successfully created:

    *   2 Users
    *   8 Events